let xRita = 50;
let yRita = 10;
let sumaRita = xRita + yRita;
let skirtumasRita = xRita - yRita;
let daugybaRita = xRita * yRita;
let dalybaRita = xRita / yRita;
console.log('Ritos sudetis', sumaRita);
console.log('Ritos atimtis', skirtumasRita);
console.log('Ritos daugyba', daugybaRita);
console.log('Ritos dalyba', dalybaRita);
